export { default } from "./Home";
export { default as TrendCollection } from "./TrendCollection";
export { default as SpecialPrice } from "./SpecialPrice";
export { default as Offers } from "./Offers";
export { default as VideoOffer } from "./VideoOffer";
export { default as LatestBlogs } from "./LatestBlogs";
export { default as BlogItems } from "./BlogItems";
export { default as Features } from "./Features";
export { default as FeatureItems } from "./FeatureItems";
export { default as BestProducts } from "./BestProducts";
export { default as BestProItems } from "./BestProItems";
export { default as CustomerReview } from "./CustomerReview";
export { default as Faqs } from "./Faqs";
