export { default as InstagramLogo } from "./InstagramLogo";
export { default as FaceBookLogo } from "./FaceBookLogo";
export { default as TwitterLogo } from "./TwitterLogo";
export { default as PinterestLogo } from "./PinterestLogo";
export { default as BasketSvg } from "./BasketSvg";
export { default as SearchSvg } from "./SearchSvg";
export { default as UserSvg } from "./UserSvg";
export { default as AvatarSvg } from "./AvatarSvg";
export { default as CartCounter } from "./CartCounter";
